#!/usr/bin/env python3
import os
import sys

import splitwork


if __name__ == "__main__":
    stdin = sys.stdin.fileno()
    stdout = sys.stdout.fileno()
    args = sys.argv[1:]
    if not args:
        raise Exception("Subcommand needed")
    f = splitwork.execvp_subprocess(args[0], args)
    pids, _ = splitwork.round_robin_split(f, stdin, file_out=stdout, N=10)
    for pid in pids:
        os.waitpid(pid, 0)
