#!/usr/bin/env python3
import os
import io
import sys

import splitwork


def wcl(fin, fout):
    i = 0
    for _ in fin:
        i += 1
    fout.write((str(i) + '\n').encode())


def cat(fin, fout):
    for line in fin:
        fout.write(line)


def execvp_subprocess(path, args):
    def __subprocess(fin, fout):
        os.dup2(fin.fileno(), sys.stdin.fileno(), inheritable=True)
        os.dup2(fout.fileno(), sys.stdout.fileno(), inheritable=True)
        os.execvp(path, args)
    return __subprocess


if __name__ == "__main__":
    stdin = io.FileIO(sys.stdin.fileno())
    stdout = io.FileIO(sys.stdout.fileno(), "w")
    args = sys.argv[1:]
    if not args:
        raise Exception("Subcommand needed")
    f = execvp_subprocess(args[0], args)
    pids, fout = splitwork.round_robin_split(f, stdin, file_out=stdout, N=10)
    for pid in pids:
        os.waitpid(pid, 0)
